#!/usr/bin/env bash
# Render /etc/clirelay-cluster/patroni.yml for one node from a node env file.
#
# Usage: render-patroni.sh <node.env> > patroni.yml
#
# node.env provides (see node.env.example):
#   NODE_NAME            unique member name, e.g. n156
#   NODE_ADDR            address other members use to reach this node
#   PG_LISTEN            comma-separated listen addresses, e.g. 127.0.0.1,156.225.27.154
#   PG_PORT              PostgreSQL port (55432 keeps the single-node DSN valid)
#   REST_PORT            Patroni REST port (8008)
#   ETCD_HOSTS           comma-separated etcd client endpoints host:port
#   PEER_CIDRS           space-separated CIDRs allowed in over TLS (cluster members)
#   LOCAL_CIDRS          space-separated CIDRs for same-host clients (127.0.0.1/32)
#   PG_SUPERUSER / PG_SUPERUSER_PASSWORD
#   PG_REPLICATION_PASSWORD
#   SHARED_BUFFERS, EFFECTIVE_CACHE_SIZE, WORK_MEM, MAINTENANCE_WORK_MEM
#   STANDBY_HOST / STANDBY_PORT / STANDBY_SLOT   optional: bootstrap as a
#       standby cluster that follows an external primary (migration only)
#   TLS_DIR              directory with ca.crt/node.crt/node.key inside the container
set -euo pipefail

env_file="${1:?usage: render-patroni.sh <node.env>}"
# shellcheck disable=SC1090
set -a
. "$env_file"
set +a

: "${NODE_NAME:?}" "${NODE_ADDR:?}" "${PG_LISTEN:?}" "${ETCD_HOSTS:?}"
: "${PG_SUPERUSER_PASSWORD:?}" "${PG_REPLICATION_PASSWORD:?}" "${PEER_CIDRS:?}"
PG_PORT="${PG_PORT:-55432}"
REST_PORT="${REST_PORT:-8008}"
PG_SUPERUSER="${PG_SUPERUSER:-cliproxy}"
LOCAL_CIDRS="${LOCAL_CIDRS:-127.0.0.1/32}"
TLS_DIR="${TLS_DIR:-/tls}"
SHARED_BUFFERS="${SHARED_BUFFERS:-256MB}"
EFFECTIVE_CACHE_SIZE="${EFFECTIVE_CACHE_SIZE:-1GB}"
WORK_MEM="${WORK_MEM:-8MB}"
MAINTENANCE_WORK_MEM="${MAINTENANCE_WORK_MEM:-128MB}"
REST_LISTEN="${REST_LISTEN:-0.0.0.0}"

yaml_quote() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/''/g")"; }

cat <<YAML
# Generated by render-patroni.sh for ${NODE_NAME}; edit node.env, not this file.
scope: clirelay
namespace: /clirelay/
name: ${NODE_NAME}

log:
  level: INFO

restapi:
  listen: ${REST_LISTEN}:${REST_PORT}
  connect_address: ${NODE_ADDR}:${REST_PORT}
  certfile: ${TLS_DIR}/node.crt
  keyfile: ${TLS_DIR}/node.key
  cafile: ${TLS_DIR}/ca.crt
  # Members call each other's REST API during leader races; every caller
  # (members, patronictl, the DNS watcher) presents a cluster certificate.
  verify_client: required

ctl:
  certfile: ${TLS_DIR}/node.crt
  keyfile: ${TLS_DIR}/node.key
  cacert: ${TLS_DIR}/ca.crt

etcd3:
  hosts: ${ETCD_HOSTS}
  protocol: https
  cacert: ${TLS_DIR}/ca.crt
  cert: ${TLS_DIR}/node.crt
  key: ${TLS_DIR}/node.key

bootstrap:
  dcs:
    # ttl bounds how long a dead primary keeps the leader key; loop_wait is
    # the HA loop period. Failover after a hard crash takes about ttl +
    # loop_wait (30-40s).
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 16777216
    primary_start_timeout: 60
    # failsafe_mode stays off: with it on, an isolated primary first tries
    # to reach every member before demoting, and the lab measured that this
    # pushes the demotion past the leader-key TTL, so both sides are primary
    # for a few seconds. etcd runs on three hosts, so losing it while both
    # PostgreSQL hosts are healthy is the rarer failure.
    failsafe_mode: false
    # Turned on once a replica exists: commits then wait for the replica,
    # and Patroni drops back to asynchronous replication when it is gone
    # (strict mode off). A replica that hangs without closing its
    # connection still holds commits until it is noticed: about 32s with
    # the default wal_sender_timeout (the member key expiring), 15-19s with
    # the 15s set below, measured by freezing the standby in the lab.
    synchronous_mode: false
    synchronous_mode_strict: false
    postgresql:
      use_pg_rewind: true
      use_slots: true
      parameters:
        max_connections: 200
        max_wal_senders: 10
        max_replication_slots: 10
        max_worker_processes: 8
        max_prepared_transactions: 0
        max_locks_per_transaction: 64
        wal_level: replica
        hot_standby: 'on'
        wal_log_hints: 'on'
        wal_keep_size: 1GB
        max_slot_wal_keep_size: 8GB
        hot_standby_feedback: 'on'
        # Detects a hung synchronous standby in 15s instead of 60s. Shorter
        # would cut replication during the few-second I/O stalls some hosts
        # show; those stalls hold commits for their own length either way.
        wal_sender_timeout: 15s
        password_encryption: scram-sha-256
        ssl: 'on'
        ssl_cert_file: ${TLS_DIR}/node.crt
        ssl_key_file: ${TLS_DIR}/node.key
        ssl_ca_file: ${TLS_DIR}/ca.crt
        tcp_keepalives_idle: 30
        tcp_keepalives_interval: 10
        tcp_keepalives_count: 3
YAML

if [ -n "${STANDBY_HOST:-}" ]; then
  cat <<YAML
    # Migration only: follow the existing single-node primary until the
    # planned switchover removes this block (patronictl edit-config).
    standby_cluster:
      host: ${STANDBY_HOST}
      port: ${STANDBY_PORT:-5432}
      primary_slot_name: ${STANDBY_SLOT:-clirelay_standby}
      create_replica_methods:
        - basebackup
YAML
fi

cat <<YAML

postgresql:
  listen: ${PG_LISTEN}:${PG_PORT}
  connect_address: ${NODE_ADDR}:${PG_PORT}
  data_dir: /var/lib/postgresql/data/pgdata
  bin_dir: /usr/local/bin
  pgpass: /tmp/pgpass0
  authentication:
    superuser:
      username: ${PG_SUPERUSER}
      password: $(yaml_quote "$PG_SUPERUSER_PASSWORD")
    replication:
      username: replicator
      password: $(yaml_quote "$PG_REPLICATION_PASSWORD")
      sslmode: verify-ca
      sslrootcert: ${TLS_DIR}/ca.crt
      sslcert: ${TLS_DIR}/node.crt
      sslkey: ${TLS_DIR}/node.key
    rewind:
      username: ${PG_SUPERUSER}
      password: $(yaml_quote "$PG_SUPERUSER_PASSWORD")
      sslmode: verify-ca
      sslrootcert: ${TLS_DIR}/ca.crt
      sslcert: ${TLS_DIR}/node.crt
      sslkey: ${TLS_DIR}/node.key
  parameters:
    unix_socket_directories: /var/run/postgresql
    shared_buffers: ${SHARED_BUFFERS}
    effective_cache_size: ${EFFECTIVE_CACHE_SIZE}
    work_mem: ${WORK_MEM}
    maintenance_work_mem: ${MAINTENANCE_WORK_MEM}
  # Same-host clients authenticate with a password; everything that crosses
  # the network must use TLS with a certificate issued by the cluster CA.
  pg_hba:
    - local all all trust
YAML
for cidr in $LOCAL_CIDRS; do
  echo "    - host all all ${cidr} scram-sha-256"
  echo "    - host replication all ${cidr} scram-sha-256"
done
for cidr in $PEER_CIDRS; do
  echo "    - hostssl replication replicator ${cidr} scram-sha-256 clientcert=verify-ca"
  echo "    - hostssl all all ${cidr} scram-sha-256 clientcert=verify-ca"
done
cat <<YAML
    - host all all 0.0.0.0/0 reject
    - host all all ::/0 reject
  pg_ctl_timeout: 60
  # Never delete a data directory automatically; a human decides after a
  # diverged timeline or a failed rewind.
  remove_data_directory_on_rewind_failure: false
  remove_data_directory_on_diverged_timelines: false
  create_replica_methods:
    - basebackup
  basebackup:
    - checkpoint: fast
    - max-rate: 60M

watchdog:
  mode: 'off'

tags:
  nofailover: false
  noloadbalance: false
  clonefrom: false
  nosync: false
YAML
