package sharedstate

import (
	"context"
	"fmt"
	"time"

	"github.com/redis/go-redis/v9"
	"github.com/router-for-me/CLIProxyAPI/v6/internal/cluster/sharedredis"
)

// Synthetic identifiers (upstream session ids, prompt cache keys, cloaked user
// ids) are random values minted once per conversation and then reused. Each
// node keeps its own cache of them; in a cluster the value has to be minted
// once for the whole cluster, or two nodes serving one conversation send the
// upstream two different sessions and each turn misses the other's prompt
// cache.
//
// The candidate is generated by the caller in exactly the format it always
// used; Redis only decides which candidate wins. The identifier's shape is
// part of the client fingerprint and must not change because of clustering.

// mintIDScript is SET NX with a readback: the first candidate wins and every
// later caller gets the winner.
//
// KEYS[1] id   ARGV[1] candidate   ARGV[2] TTL (ms)
// ARGV[3] "1" to extend the TTL when an existing id is read (sliding expiry)
// Returns {id, remaining TTL (ms), minted (0/1)}.
var mintIDScript = redis.NewScript(`
if redis.call('SET', KEYS[1], ARGV[1], 'NX', 'PX', ARGV[2]) then
  return {ARGV[1], tonumber(ARGV[2]), 1}
end
local id = redis.call('GET', KEYS[1])
if ARGV[3] == '1' then
  redis.call('PEXPIRE', KEYS[1], ARGV[2])
  return {id, tonumber(ARGV[2]), 0}
end
return {id, redis.call('PTTL', KEYS[1]), 0}
`)

// MintedID is the cluster's identifier for one key.
type MintedID struct {
	ID string
	// TTL is how long the identifier remains valid. Local caches must not keep
	// it longer, or they would outlive the shared value and diverge from the
	// node that mints its successor.
	TTL time.Duration
	// Minted reports whether the caller's candidate won.
	Minted bool
}

// MintID returns the cluster-wide identifier for (namespace, key), storing
// candidate when there is none. With sliding set, reading an existing
// identifier extends its TTL, matching caches whose entries live as long as
// they keep being used; otherwise the identifier expires ttl after it was
// minted. key is hashed before it reaches Redis.
func (s *Store) MintID(ctx context.Context, namespace, key, candidate string, ttl time.Duration, sliding bool) (MintedID, error) {
	if !s.Available() {
		return MintedID{}, sharedredis.ErrUnavailable
	}
	slide := "0"
	if sliding {
		slide = "1"
	}
	redisKey := sharedredis.KeyPrefix + "sid:" + namespace + ":" + sharedredis.HashPart(namespace, key)
	res, err := s.client.Eval(ctx, mintIDScript, []string{redisKey}, candidate, ttl.Milliseconds(), slide)
	if err != nil {
		return MintedID{}, err
	}
	list, ok := res.([]any)
	if !ok || len(list) < 3 {
		return MintedID{}, fmt.Errorf("sharedstate: unexpected mint reply %T %v", res, res)
	}
	id, ok := list[0].(string)
	if !ok || id == "" {
		return MintedID{}, fmt.Errorf("sharedstate: unexpected minted id %v", list[0])
	}
	remaining, _ := list[1].(int64)
	minted, _ := list[2].(int64)
	out := MintedID{ID: id, TTL: time.Duration(remaining) * time.Millisecond, Minted: minted == 1}
	if out.TTL <= 0 || out.TTL > ttl {
		// PTTL is -1 for a key without expiry (only possible if something else
		// wrote it) and can never exceed what we set; clamp both to ttl.
		out.TTL = ttl
	}
	return out, nil
}
